#pragma once

#include "driver/gpio.h"
#include "driver/ledc.h"

#define APP_PROJECT_NAME "Frieren"

#define APP_SOFTAP_SSID "Frieren"
#define APP_SOFTAP_IP "192.168.1.4"
#define APP_HTTP_PORT 80
#define APP_WIFI_MAX_CONNECTIONS 4

#define APP_GPIO_KEY_SENSE GPIO_NUM_5
#define APP_GPIO_USB_PRESENT GPIO_NUM_7
#define APP_GPIO_LIGHT_PWM GPIO_NUM_6

#define APP_PWM_MODE LEDC_LOW_SPEED_MODE
#define APP_PWM_TIMER LEDC_TIMER_0
#define APP_PWM_CHANNEL LEDC_CHANNEL_0
#define APP_PWM_FREQUENCY_HZ 5000
#define APP_PWM_RESOLUTION LEDC_TIMER_13_BIT
#define APP_PWM_DUTY_MAX 8191

#define APP_EFFECT_TASK_STACK_SIZE 4096
#define APP_EFFECT_TASK_PRIORITY 5
#define APP_EFFECT_TASK_PERIOD_MS 20

#define APP_INPUT_POLL_PERIOD_MS 100
#define APP_INPUT_DEBOUNCE_MS 30
